### ISSUE TITLE
Referer checking on the backend

### ISSUE THREAD

**Issue by coandco** [coandco/CardMachine#11]
The PHP file should only allow requests with referer set to one of a few whitelisted domains (tsssf.twentymine.com, Latent's github.io, etc).

**Comment by Latent-Logic** [comment]
Related, but not overriding this:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://tsssf...com/TSSSF/ponyimage.php. (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

**Comment by coandco** [comment]
The cross-origin stuff is now implemented.  I'm not sure how redundant it makes the referer checking.

**Comment by coandco** [comment]
I'm going to close this for now, as the cross-origin stuff serves the same purpose and is actually necessary.
